// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_CONTACTS_DATA = "GET_CONTACTS_DATA";
export const GET_REF_DATA= "GET_REF_DATA";
export const GET_CONTACTS_DETAIL = "GET_CONTACTS_DETAIL";
